version: '3.8'

services:
  scraper:
    build: .
    container_name: scrape-and-notify
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Uncomment and configure if you need to expose ports
    # ports:
    #   - "8000:8000"
    
    # Uncomment and configure if you need environment variables
    # env_file:
    #   - .env
    
    # For development, you can mount the source code
    # volumes:
    #   - .:/app
    #   - ./logs:/app/logs
    
    # If you need to run periodically instead of continuously
    # Use this configuration instead:
    # command: ["sh", "-c", "while true; do poetry run python src/main.py; sleep 3600; done"] 